#import "../../category/fragments/CategoryBasic.gql"
#import "../../collection/fragments/CollectionBasic.gql"

fragment BasicProductFields on Product {
  id
  name
  slug
  isAvailable
  isAvailableForPurchase
  category {
    ...CategoryBasic
  }
  collections {
    ...CollectionBasic
  }
}
