fragment ProductPricingField on Product {
  pricing {
    onSale
    priceRangeUndiscounted {
      start {
        ...Price
      }
      stop {
        ...Price
      }
    }
    priceRange {
      start {
        ...Price
      }
      stop {
        ...Price
      }
    }
  }
}
