#import "./Price.gql"

fragment VariantFragment on ProductVariant {
  id
  sku
  attributes {
    attribute {
      name
      slug
      id
      isColor
    }
    values {
      id
      slug
      name
      value
    }
  }
  pricing {
    priceLocalCurrency {
      ...Price
    }
  }
  isAvailable
}
