#import "./addressFragment.gql"
#import "../../products/fragments/Price.gql"
#import "./orderLineDetailFragment.gql"

fragment OrderDetailFragment on Order {
  __typename
  id
  number
  created
  status
  statusDisplay
  lines {
    ...OrderLineDetailFragment
  }
  user {
    firstName
    lastName
    email
  }
  billingAddress {
    ...AddressFragment
  }
  shippingAddress {
    ...AddressFragment
  }
  shippingMethodName
  total {
    ...Price
  }
  shippingPrice {
    ...Price
  }
  paymentStatusDisplay
  subtotal {
    ...Price
  }
}
