#import "../../products/fragments/Money.gql"

fragment ShippingMethodFragment on ShippingMethod {
  id
  name
  price {
    amount
    currency
  }
  minimumOrderPrice {
    ...MoneyFragment
  }
  maximumOrderPrice {
    ...MoneyFragment
  }
  minimumOrderWeight {
    unit
    value
  }
  maximumOrderWeight {
    unit
    value
  }
  type
}
